Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GamMaSite.Models;
using GamMaSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GamMaSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MessagesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<SiteUser> _userManager;
        private readonly ISmsSender _smsSender;
        private readonly IEmailService _emailService;
        public MessagesController(RoleManager<IdentityRole> roleMgr, UserManager<SiteUser> userMrg, ISmsSender smsSdr, IEmailService emailService)
        {
            _roleManager = roleMgr;
            _userManager = userMrg;
            _smsSender = smsSdr;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            var userCategories = new UserCategories(_roleManager, _userManager);
            return View(userCategories);
        }

        public async Task<IActionResult> Send(UserStatus[] status, string role, MessageMedia media, string subject, string messageBody, string smsBody)
        {
            var usersToReceiveMessage = _userManager.Users.Where(user => status.Contains(user.Status)).ToHashSet();
            if (!String.IsNullOrEmpty(role))
            {
                usersToReceiveMessage.UnionWith(await _userManager.GetUsersInRoleAsync(role));
            }
            if (media == MessageMedia.SMS || media == MessageMedia.EmailSMS)
            {
                var userPhonenumbers = usersToReceiveMessage.Where(user => !string.IsNullOrEmpty(user?.PhoneNumber)).Select(user => user.PhoneNumber).ToArray();
                var result = await _smsSender.SendSmsAsync(smsBody, userPhonenumbers);
            }
            if (media == MessageMedia.Email || media == MessageMedia.EmailSMS)
            {
                var mails = usersToReceiveMessage.Where(user => !string.IsNullOrEmpty(user?.Email)).Select(user => user.Email).ToArray();
                await _emailService.SendEmailAsync(mails, subject, messageBody);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Messages/Index.cshtml
@model UserCategories

<h1>Send besked</h1>
<form asp-action="Send" asp-controller="Messages" method="post" id="messageForm">
    <div class="d-grid gap-1">
        <div class="input-group form-group p-1">
            <select multiple="multiple" name="status" class="selectpicker form-control" title="Vælg gruppe...">
                @foreach (var status in @Model.Status)
                {
                <option value="@status">@status</option>
                }
            </select>
            <span class="input-group-addon">&nbsp;&nbsp;&nbsp;</span>
            <select multiple="multiple" name="role" class="selectpicker form-control" title="Vælg rolle...">
                @foreach (var role in @Model.Roles)
                {
                <option value="@role.Name">@role.Name</option>
                }
            </select>
        </div>
        <div class="form-group p-1">
            <input type="radio" name="media" value="Email" checked>&nbsp;Email&nbsp;</input>
            <input type="radio" name="media" value="SMS">&nbsp;SMS&nbsp;</input>
            <input type="radio" name="media" value="EmailSMS">&nbsp;Email & SMS&nbsp;</input>
        </div>
        <div class="form-group p-1">
            <input type="text" name="subject" id="subject" class="form-control" placeholder="Emne..." />
        </div>
        <div class="form-group p-1">
            <textarea id="summernote" name="messageBody"></textarea>
        </div>
        <input class="p-1" type="hidden" id="smsBody" name="smsBody" value="" />
    </div>
</form>
<button onclick="submitform()" class="btn btn-primary">Send besked</button>
<script>
    $('#summernote').summernote({
        placeholder: 'Indtast besked...'
    });
    function submitform() {
        var subject = document.getElementById("subject").value.trim().length;
        if (subject == 0) {
            Swal.fire({
                icon: 'error',
                title: 'Hov!',
                text: 'Emnefelt skal udfyldes!'
            });
            return;
        }
        document.getElementById('smsBody').value = $($('#summernote').summernote('code')).text();
        Swal.fire({
            title: 'Vil du sende beskeden?',
            showDenyButton: true,
            confirmButtonText: `Send besked!`,
            denyButtonText: `Annullér`,
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                document.getElementById("messageForm").submit();
            }
        });
    };
</script>